info:
  component: Edge server (based on Netflix Zuul)

spring:
  application:
    name: edge-server
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20
      discovery:
        serviceId: config-server
        enabled: false
      uri: https://localhost:8888

#eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka