server:
  port: ${port:8080}
#management endpoints on a separate port
#management:
#  port: 8091
#  security:
#    enabled: false # management port is internal only. no need to secure it.
jwt:
  header: Authorization
  auth-uri: /auth/**
  secret: dothat
  prefix: Bearer
  expiration: '86400'

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  main:
    allow-bean-definition-overriding: 'true'
  application.name: spring-server
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  cloud:
#    config:
#      failFast: true
#      retry:
#        initialInterval: 3000
#        multiplier: 1.3
#        maxInterval: 5000
#        maxAttempts: 20
##      discovery:
#        serviceId: config-server
#        enabled: false
#      uri: https://localhost:8888

  # ===============================
  # = Mysql configurations
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/dothatspring?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Dothat998
  # ===============================
  # = Redis configurations
  # ===============================ß
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 5
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000
# hazelcast.yaml
  hazelcast:
    network:
      join:
        multicast:
          enabled: true
  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    database: MYSQL
    show-sql: true
    hb2dll:
      auto: update
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Logging configurations
# ===============================
#logging:
#  pattern:
#    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36}.%M - %msg%n"
#    file: "%d %-5level [%thread] %logger{0} : %msg%n"
#  level:
#    root: WARN
#    com.irsyad.springmysqlredis: DEBUG
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#    org:
#      hibernate.SQL: DEBUG
#      hibernate.type.descriptor.sql.BasicBinder: TRACE


#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
