server:
  port: '8082'
spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  main:
    allow-bean-definition-overriding: 'true'
  application.name: review-service
  cloud:
    config:
      failFast: true
      retry:
        initialInterval: 3000
        multiplier: 1.3
        maxInterval: 5000
        maxAttempts: 20
      discovery:
        serviceId: config-server
        enabled: false
      uri: https://localhost:8888

